### ISSUE TITLE
Nothing works including forums

### ISSUE THREAD

**Issue by williamgall** [divix1988/laminas-cli-commands#1]
Downloaded and installed the local commands and can't get anything but exceptions on CentOS with php7.4. I tried to register at the forum to ask for help but it never sends an email to activate my account. Looks promising though. What are the php version requirements ?

**Comment by divix1988** [comment]
Hello William,

I did manage to fix the mail configuration on the forum, so the activation links should be now sent correctly.
I have also manually enabled your account so you should be able to login to site.

The PHP requirement is 7.4 or later.

Can you paste the error log which you get when running a command? Also which command have you tried? I suggest you start from simple Model, View or Controller generator first before heading to mode advanced, so we can easier narrow down the issue on CentOS.
