### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Laminas\Code\Generator\ClassGenerator' not found in C:\xampp\htdocs\laminas_mvc\vendor\divix1988\laminas-cli-commands\src\ModelCommand.php:54

### ISSUE THREAD

**Issue by cwakelee** [divix1988/laminas-cli-commands#2]
PHP Fatal error:  Uncaught Error: Class 'Laminas\Code\Generator\ClassGenerator' not found in C:\xampp\htdocs\laminas_mvc\vendor\divix1988\laminas-cli-commands\src\ModelCommand.php:54

**Comment by divix1988** [comment]
You are missing laminas-code package in your composer, run this:

`composer require laminas/laminas-code`

**Comment by divix1988** [comment]
I've added missing dependency just now: https://github.com/divix1988/laminas-cli-commands/commit/12e5973c714815c8628ed85c96912bc4d0f79c1c
