### ISSUE TITLE
PHP Warning:  file_get_contents(C:\xampp\htdocs\laminas_mvc2\module\Login\config\module.config.php): failed to open stream: No such file or directory in C:\xampp\htdocs\laminas_mvc2\vendor\divix1988\laminas-cli-commands\src\AbstractCommand.php on line 386

### ISSUE THREAD

**Issue by cwakelee** [divix1988/laminas-cli-commands#3]
PHP Warning:  file_get_contents(C:\xampp\htdocs\laminas_mvc2\module\Login\config\module.config.php): failed to open stream: No such file or directory in C:\xampp\htdocs\laminas_mvc2\vendor\divix1988\laminas-cli-commands\src\AbstractCommand.php on line 386

**Comment by divix1988** [comment]
Make sure you have module called `Login` in your laminas skeleton (`[root]\module\Login\`).

I strongly recommend re-using default one called `Application` instead for simple use-cases.
