### ISSUE TITLE
This is with your demo. C:\xampp\htdocs\laminas_demo\vendor\laminas\laminas-view\src\Renderer\PhpRenderer.php:497

### ISSUE THREAD

**Issue by cwakelee** [divix1988/laminas-cli-commands#4]
C:\xampp\htdocs\laminas_demo\vendor\laminas\laminas-view\src\Renderer\PhpRenderer.php:497

any help would be apricated.

**Comment by divix1988** [comment]
@cwakelee  Thanks for the report. Can you paste the whole error message and when this thing is happening?
