### ISSUE TITLE
on http://localhost/laminas_demo/login/progressuser error

### ISSUE THREAD

**Issue by cwakelee** [divix1988/laminas-cli-commands#5]
Error :(
500
An error occurred error during processing, please try again or report a problem.
Take me back to Home Page Report an issue
Additional information:
Laminas\View\Exception\RuntimeException
File:
C:\xampp2\htdocs\laminas_demo\vendor\laminas\laminas-view\src\Renderer\PhpRenderer.php:497
Message:
Laminas\View\Renderer\PhpRenderer::render: Unable to render template "application/login/progressuser"; resolver could not resolve to a file
Stack trace:
#0 C:\xampp2\htdocs\laminas_demo\vendor\laminas\laminas-view\src\View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#1 C:\xampp2\htdocs\laminas_demo\vendor\laminas\laminas-view\src\View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#2 C:\xampp2\htdocs\laminas_demo\vendor\laminas\laminas-view\src\View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#3 C:\xampp2\htdocs\laminas_demo\vendor\laminas\laminas-mvc\src\View\Http\DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#4 C:\xampp2\htdocs\laminas_demo\vendor\laminas\laminas-eventmanager\src\EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#5 C:\xampp2\htdocs\laminas_demo\vendor\laminas\laminas-eventmanager\src\EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#6 C:\xampp2\htdocs\laminas_demo\vendor\laminas\laminas-mvc\src\Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#7 C:\xampp2\htdocs\laminas_demo\vendor\laminas\laminas-mvc\src\Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#8 C:\xampp2\htdocs\laminas_demo\public\index.php(54): Laminas\Mvc\Application->run()
#9 C:\xampp2\htdocs\laminas_demo\index.php(1): include('C:\\xampp2\\htdoc...')
#10 {main}

**Comment by divix1988** [comment]
Check what role your user have. The demo only support 3 types: `admin`, `super_admin` and `user`. 
You check that by altering `progressUserAction()` with:
```
    public function progressUserAction()
    {
        $sessionUser = new Session\Container('user');

        if (!empty($this->params()->fromQuery('redirectTo'))) {
            return $this->redirect()->toUrl($this->params()->fromQuery('redirectTo'), 302);
        }

        if ($sessionUser->details->getRole() === 'admin' || $sessionUser->details->getRole() === 'super_admin') {
            return $this->redirect()->toRoute('admin', ['controller' => 'IndexController', 'action' => 'index']);
        } else if($sessionUser->details->getRole() === 'user') {
            return $this->redirect()->toRoute('user');
        } else {
            exit('Unsupported user role: '.$sessionUser->details->getRole());
        }
    }
```
