### ISSUE TITLE
I have a problem with the installation.

### ISSUE THREAD

**Issue by WDSB** [divix1988/laminas-cli-commands#7]
I have a problem with the installation.

When I call composer require --dev divix1988 / laminas-cli-commands I always get the following error message

  Problem 1
    - Root composer.json requires divix1988/laminas-cli-commands ^1.1 -> satisfiable by divix1988/laminas-cli-commands[1.1].
    - divix1988/laminas-cli-commands 1.1 requires laminas/laminas-cli ^0.1.4 -> found laminas/laminas-cli[0.1.4, 0.1.5, 0.1.6] but it conflicts with your root composer.json require (^1.1.1).

**Comment by divix1988** [comment]
@WDSB  sorry for late response.

I have updated the the dependencies to match the latest versions. You should be able to include `divix1988/laminas-cli-commands` now into your project. Just make sure to target the newest 1.3.1 release at least:

```
composer require --dev divix1988/laminas-cli-commands 1.3.1
```

Result:
```
composer require --dev divix1988/laminas-cli-commands 1.3.1
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing divix1988/laminas-cli-commands (1.3.1): Downloading (100%)
Writing lock file
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
```

Let me know if you get any more issues.
