### ISSUE TITLE
I have a problem with the command mvc:crud

### ISSUE THREAD

**Issue by ZepiDarmawanTambunan** [divix1988/laminas-cli-commands#9]
for example:
"vendor/bin/laminas.bat" mvc:crud --properties=title --properties=description --properties=price --module=ModuleName Books

error:
PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in C:\xampp\htdocs\laminas-mvc\vendor\divix1988\laminas-cli-commands\src\CrudCommand.php:47
Stack trace:
#0 C:\xampp\htdocs\laminas-mvc\vendor\divix1988\laminas-cli-commands\src\CrudCommand.php(47): join(Array, ', ')
#1 C:\xampp\htdocs\laminas-mvc\vendor\symfony\console\Command\Command.php(326): Divix\Laminas\Cli\Command\CrudCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\xampp\htdocs\laminas-mvc\vendor\symfony\console\Application.php(1081): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\xampp\htdocs\laminas-mvc\vendor\symfony\console\Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Divix\Laminas\Cli\Command\CrudCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\xampp\htdocs\laminas-mvc\vendor\symfony\console\Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\laminas-mvc\vendor\laminas\laminas-cli\bin\laminas(53): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\laminas-mvc\vendor\bin\laminas(119): include('C:\\xampp\\htdocs...')
#7 {main}
  thrown in C:\xampp\htdocs\laminas-mvc\vendor\divix1988\laminas-cli-commands\src\CrudCommand.php on line 47

Fatal error: Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in C:\xampp\htdocs\laminas-mvc\vendor\divix1988\laminas-cli-commands\src\CrudCommand.php:47
Stack trace:
#0 C:\xampp\htdocs\laminas-mvc\vendor\divix1988\laminas-cli-commands\src\CrudCommand.php(47): join(Array, ', ')
#1 C:\xampp\htdocs\laminas-mvc\vendor\symfony\console\Command\Command.php(326): Divix\Laminas\Cli\Command\CrudCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\xampp\htdocs\laminas-mvc\vendor\symfony\console\Application.php(1081): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\xampp\htdocs\laminas-mvc\vendor\symfony\console\Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Divix\Laminas\Cli\Command\CrudCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\xampp\htdocs\laminas-mvc\vendor\symfony\console\Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\laminas-mvc\vendor\laminas\laminas-cli\bin\laminas(53): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\laminas-mvc\vendor\bin\laminas(119): include('C:\\xampp\\htdocs...')
#7 {main}
  thrown in C:\xampp\htdocs\laminas-mvc\vendor\divix1988\laminas-cli-commands\src\CrudCommand.php on line 47

**Comment by divix1988** [comment]
@ZepiDarmawanTambunan did you modify any of the vendor lib files? Also, are you on `master` branch?

I've just tried running your command and it works as expected:
```
"vendor/bin/laminas.bat" mvc:crud --properties=title --properties=description --properties=price --module=ModuleName Books

Start creating a CRUD with properties: title, description, price
Start creating new Controller: Controller/BooksController.php
End creating new Controller.
Start creating new Model: Model/BooksTable.php
End creating new Model.
Start creating new Rowset: Model/Rowset/Book.php
End creating new Rowset.
Start creating new Form: Form/BookForm.php
End creating new Form.
Start creating Views for: index.phtml, create.phtml, update.phtml and delete.phtml.
End creating new Views.
Start creating new Config: config/generated.crud.php
End creating new Config.
Start creating SQL script: sql/crud_Books.sql
End creating SQL script.
Done creating new CRUD.
```

Line `47` is just a log line:
```
$section1->writeln('Start creating a CRUD with properties: '.join($properties, ', '));
```
and `getPropertiesArray()` method always returns an array:
```
protected function getPropertiesArray($input, $alias = 'properties'): array
```
